name: Check changelog file included

on:
  pull_request:
    paths:
      - 'release_tools/**'

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: bitergia/release-tools-check-changelog@master
